name: patrol_cursor_issue
description: A showcase for the blinking cursor golden test issue.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  golden_toolkit: ^0.15.0
  patrol: ^2.2.0

flutter:
  uses-material-design: true
